
# Theme
theme: jekyll-theme-minimal


# Theme vars
title: The Kübler Lab
description: |
  Our research focuses on molecular changes in the development of various tumors. 
  We now want to use bioinformatic and experimental methods to better understand the early development of cancer 
  in order to be able to intervene and prevent it in the long term.
  <br>
  <a href="index.html">Projects</a> | 
  <a href="team.html">Team</a>

logo: assets/logo.png
github:
  is_user_page: false



# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
